export const UI_TEXT = {
  common: {
    loading: '読み込み中...',
    error: 'エラーが発生しました',
    notFound: '見つかりません',
    back: '戻る',
    close: '閉じる',
    cancel: 'キャンセル',
    confirm: '確認',
    submit: '送信',
    total: '合計',
    processing: '処理中...',
  },
  menu: {
    title: 'メニュー',
    categories: {
      all: '全て',
      bento: '弁当',
      curry: 'カレー',
      side: 'サイド',
      drink: 'ドリンク',
      yakitori: '焼き鳥',
    },
    item: {
      title: '商品詳細',
      quantity: '数量',
      customization: 'カスタマイズ',
      description: '商品説明',
      itemTotal: '商品合計',
      cartTotal: '注文合計',
      addToCart: '注文に追加',
      unavailable: '現在ご注文いただけません',
      units: '個',
    },
    help: {
      title: 'お問い合わせ',
      message: 'お問い合わせは以下の連絡先までお願いいたします：',
      phone: '電話番号',
      hours: '受付時間',
      email: 'メール',
    },
    customization: {
      extraLarge: '大盛り',
      lessRice: 'ご飯少なめ',
      extraMeat: '増量',
      noWasabi: 'わさび抜き',
      spicyLevel: '辛さ増し',
      onsenEgg: '温泉卵トッピング',
      sauce: 'タレ',
      salt: '塩',
      noEgg: '玉子黄身なし',
    },
  },
  cart: {
    title: '注文内容',
    empty: '注文が空です',
    backToMenu: 'メニューに戻る',
    total: '合計金額',
    customerInfo: 'お客様情報',
    payment: {
      title: 'お支払い方法',
      cash: '現金',
      paypay: 'PayPay',
      payLater: '(受け取り時に決済)',
      completed: '支払い完了',
      pending: '未決済',
    },
    receipt: '領収書が必要',
    form: {
      name: {
        last: '姓',
        first: '名',
        placeholder: {
          last: '山田',
          first: '太郎',
        },
      },
      company: {
        name: '会社名',
        optional: '(任意)',
      },
      address: {
        postal: '郵便番号',
        prefecture: '都道府県',
        city: '市区町村',
        line: '番地・建物名',
      },
      phone: '電話番号',
      pickup: {
        time: '受け取り時間',
        select: '選択してください',
      },
    },
    validation: {
      required: '必須項目です',
      nameFormat: '有効な名前を入力してください',
      postalCode: '正しい郵便番号を入力してください（例：100-0005）',
      phone: '有効な電話番号を入力してください（10桁または11桁）',
      deliveryTime: {
        required: '受け取り時間を選択してください',
        invalid: '有効な受け取り時間を選択してください',
        range: '受け取り時間は営業時間内で指定してください',
      },
    },
    order: {
      submit: '注文を確定する',
      processing: '処理中...',
    },
    confirm: {
      title: '注文内容の確認',
      pickupDate: '受け取り日',
      pickupTime: '受け取り時間',
      totalAmount: '合計金額',
      cancelNote: '受け取り60分前まで注文履歴からキャンセルできます',
      back: '戻る',
      submit: '注文を確定する',
      todayBadge: '今日',
      tomorrowBadge: '明日',
    },
    dateNotice: {
      holiday: '本日は臨時休業日のため、翌営業日からご注文いただけます。',
      closed: '本日は定休日のため、翌営業日からご注文いただけます。',
      deadlinePassed: '本日分の受付は終了しました。翌営業日からご注文いただけます。',
    },
    orderType: {
      title: '受け取り方法',
      pickup: '店頭受取',
      delivery: 'お届け',
      unavailableToday: '本日不可',
    },
    fulfillment: {
      sectionTitle: '受け取り希望日時',
      dateLabel: '受け取り日',
      timeLabel: '受け取り時間',
      timeSelect: '時間を選択してください',
      noSlotsAvailable: '選択された日は予約可能な時間がありません',
      notesLabel: '備考',
      notesPlaceholder: 'アレルギーなどの注意事項があればご記入ください',
    },
    minOrderNotMet: '最低注文金額に達していません',
    minOrderDetail: '合計で ¥{amount} 以上の注文が必要です（現在: ¥{current}）',
    loginRequired: '注文するにはログインが必要です',
  },
  order: {
    status: {
      title: '注文状況',
      pending: '確認中',
      accepted: '受付済み',
      preparing: '調理中',
      delivering: '配達中',
      completed: '完了',
      cancelled: 'キャンセル',
      completed_long: 'お渡し完了',
      cancelled_long: 'キャンセル済み',
    },
    detail: {
      title: '注文詳細',
      orderNumber: '注文番号',
      content: '注文内容',
      customerInfo: 'お客様情報',
      name: 'お名前',
      companyName: '会社名',
      address: '会社住所',
      phone: '電話番号',
      deliveryTime: '受け取り時間',
      notes: '備考',
      paymentInfo: 'お支払い情報',
      paymentMethod: 'お支払い方法',
      notFound: {
        title: '注文が見つかりません',
        message:
          '指定された注文が見つかりませんでした。\nURLを確認するか、注文履歴から選択してください。',
        action: '注文履歴に戻る',
      },
      print: {
        orderTitle: '注文確認書',
        receiptTitle: '領収書',
        customerName: 'お客様名',
        deliveryAddress: 'お届け先',
        orderDate: '注文日時',
        itemName: '品名',
        quantity: '数量',
        amount: '金額',
        thanks: 'ご注文ありがとうございました',
        seeYouAgain: 'またのご利用をお待ちしております',
      },
      action: {
        reorder: '同じ注文をする',
        reordering: '処理中...',
        print: '印刷',
        printReceipt: '領収書を印刷',
      },
    },
  },
  history: {
    title: '注文履歴',
    empty: {
      message: '注文履歴がありません',
      action: 'メニューに戻る',
    },
    orderNumber: '注文番号',
    details: '詳細を見る',
    itemCount: '品',
    loadMore: 'もっと見る',
  },
} as const;

export type UITextKey = keyof typeof UI_TEXT;
